name: SOPT Seminar Server CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ✔️ create application.yml
        run: |
          cd ./api/src/main
          mkdir resources
          cd ./resources
          echo "$APPLICATION" > ./application.yml
        env:
          APPLICATION: ${{ secrets.APPLICATION }}

      - name: ✔️ set permission
        run: chmod +x gradlew

      - name: ✔️ build gradle
        run: ./gradlew seminar-api:build